//go:build wifidebug

// Code generated by "stringer -type=CommandType -trimprefix=Cmd"; DO NOT EDIT.

package wifinina

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CmdStart-224]
	_ = x[CmdEnd-238]
	_ = x[CmdErr-239]
	_ = x[CmdSetNet-16]
	_ = x[CmdSetPassphrase-17]
	_ = x[CmdSetKey-18]
	_ = x[CmdSetIPConfig-20]
	_ = x[CmdSetDNSConfig-21]
	_ = x[CmdSetHostname-22]
	_ = x[CmdSetPowerMode-23]
	_ = x[CmdSetAPNet-24]
	_ = x[CmdSetAPPassphrase-25]
	_ = x[CmdSetDebug-26]
	_ = x[CmdGetTemperature-27]
	_ = x[CmdGetReasonCode-31]
	_ = x[CmdGetConnStatus-32]
	_ = x[CmdGetIPAddr-33]
	_ = x[CmdGetMACAddr-34]
	_ = x[CmdGetCurrSSID-35]
	_ = x[CmdGetCurrBSSID-36]
	_ = x[CmdGetCurrRSSI-37]
	_ = x[CmdGetCurrEncrType-38]
	_ = x[CmdScanNetworks-39]
	_ = x[CmdStartServerTCP-40]
	_ = x[CmdGetStateTCP-41]
	_ = x[CmdDataSentTCP-42]
	_ = x[CmdAvailDataTCP-43]
	_ = x[CmdGetDataTCP-44]
	_ = x[CmdStartClientTCP-45]
	_ = x[CmdStopClientTCP-46]
	_ = x[CmdGetClientStateTCP-47]
	_ = x[CmdDisconnect-48]
	_ = x[CmdGetIdxRSSI-50]
	_ = x[CmdGetIdxEncrType-51]
	_ = x[CmdReqHostByName-52]
	_ = x[CmdGetHostByName-53]
	_ = x[CmdStartScanNetworks-54]
	_ = x[CmdGetFwVersion-55]
	_ = x[CmdSendDataUDP-57]
	_ = x[CmdGetRemoteData-58]
	_ = x[CmdGetTime-59]
	_ = x[CmdGetIdxBSSID-60]
	_ = x[CmdGetIdxChannel-61]
	_ = x[CmdPing-62]
	_ = x[CmdGetSocket-63]
	_ = x[CmdSendDataTCP-68]
	_ = x[CmdGetDatabufTCP-69]
	_ = x[CmdInsertDataBuf-70]
	_ = x[CmdSetPinMode-80]
	_ = x[CmdSetDigitalWrite-81]
	_ = x[CmdSetAnalogWrite-82]
}

const (
	_CommandType_name_0 = "SetNetSetPassphraseSetKey"
	_CommandType_name_1 = "SetIPConfigSetDNSConfigSetHostnameSetPowerModeSetAPNetSetAPPassphraseSetDebugGetTemperature"
	_CommandType_name_2 = "GetReasonCodeGetConnStatusGetIPAddrGetMACAddrGetCurrSSIDGetCurrBSSIDGetCurrRSSIGetCurrEncrTypeScanNetworksStartServerTCPGetStateTCPDataSentTCPAvailDataTCPGetDataTCPStartClientTCPStopClientTCPGetClientStateTCPDisconnect"
	_CommandType_name_3 = "GetIdxRSSIGetIdxEncrTypeReqHostByNameGetHostByNameStartScanNetworksGetFwVersion"
	_CommandType_name_4 = "SendDataUDPGetRemoteDataGetTimeGetIdxBSSIDGetIdxChannelPingGetSocket"
	_CommandType_name_5 = "SendDataTCPGetDatabufTCPInsertDataBuf"
	_CommandType_name_6 = "SetPinModeSetDigitalWriteSetAnalogWrite"
	_CommandType_name_7 = "Start"
	_CommandType_name_8 = "EndErr"
)

var (
	_CommandType_index_0 = [...]uint8{0, 6, 19, 25}
	_CommandType_index_1 = [...]uint8{0, 11, 23, 34, 46, 54, 69, 77, 91}
	_CommandType_index_2 = [...]uint8{0, 13, 26, 35, 45, 56, 68, 79, 94, 106, 120, 131, 142, 154, 164, 178, 191, 208, 218}
	_CommandType_index_3 = [...]uint8{0, 10, 24, 37, 50, 67, 79}
	_CommandType_index_4 = [...]uint8{0, 11, 24, 31, 42, 55, 59, 68}
	_CommandType_index_5 = [...]uint8{0, 11, 24, 37}
	_CommandType_index_6 = [...]uint8{0, 10, 25, 39}
	_CommandType_index_8 = [...]uint8{0, 3, 6}
)

func (i CommandType) String() string {
	switch {
	case 16 <= i && i <= 18:
		i -= 16
		return _CommandType_name_0[_CommandType_index_0[i]:_CommandType_index_0[i+1]]
	case 20 <= i && i <= 27:
		i -= 20
		return _CommandType_name_1[_CommandType_index_1[i]:_CommandType_index_1[i+1]]
	case 31 <= i && i <= 48:
		i -= 31
		return _CommandType_name_2[_CommandType_index_2[i]:_CommandType_index_2[i+1]]
	case 50 <= i && i <= 55:
		i -= 50
		return _CommandType_name_3[_CommandType_index_3[i]:_CommandType_index_3[i+1]]
	case 57 <= i && i <= 63:
		i -= 57
		return _CommandType_name_4[_CommandType_index_4[i]:_CommandType_index_4[i+1]]
	case 68 <= i && i <= 70:
		i -= 68
		return _CommandType_name_5[_CommandType_index_5[i]:_CommandType_index_5[i+1]]
	case 80 <= i && i <= 82:
		i -= 80
		return _CommandType_name_6[_CommandType_index_6[i]:_CommandType_index_6[i+1]]
	case i == 224:
		return _CommandType_name_7
	case 238 <= i && i <= 239:
		i -= 238
		return _CommandType_name_8[_CommandType_index_8[i]:_CommandType_index_8[i+1]]
	default:
		return "CommandType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
