//go:build wifidebug

// Code generated by "stringer -type=EncryptionType -trimprefix=EncType"; DO NOT EDIT.

package wifinina

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EncTypeTKIP-2]
	_ = x[EncTypeCCMP-4]
	_ = x[EncTypeWEP-5]
	_ = x[EncTypeNone-7]
	_ = x[EncTypeAuto-8]
}

const (
	_EncryptionType_name_0 = "TKIP"
	_EncryptionType_name_1 = "CCMPWEP"
	_EncryptionType_name_2 = "NoneAuto"
)

var (
	_EncryptionType_index_1 = [...]uint8{0, 4, 7}
	_EncryptionType_index_2 = [...]uint8{0, 4, 8}
)

func (i EncryptionType) String() string {
	switch {
	case i == 2:
		return _EncryptionType_name_0
	case 4 <= i && i <= 5:
		i -= 4
		return _EncryptionType_name_1[_EncryptionType_index_1[i]:_EncryptionType_index_1[i+1]]
	case 7 <= i && i <= 8:
		i -= 7
		return _EncryptionType_name_2[_EncryptionType_index_2[i]:_EncryptionType_index_2[i+1]]
	default:
		return "EncryptionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
