package hd44780

const (
	DISPLAY_CLEAR = 0x1
	CURSOR_HOME   = 0x2

	ENTRY_MODE       = 0x4
	CURSOR_DECREASE  = ENTRY_MODE | 0x0
	CURSOR_INCREASE  = ENTRY_MODE | 0x2
	DISPLAY_SHIFT    = ENTRY_MODE | 0x1
	DISPLAY_NO_SHIFT = ENTRY_MODE | 0x0

	DISPLAY_ON_OFF   = 0x8
	DISPLAY_ON       = DISPLAY_ON_OFF | 0x4
	DISPLAY_OFF      = DISPLAY_ON_OFF | 0x0
	CURSOR_ON        = DISPLAY_ON_OFF | 0x2
	CURSOR_OFF       = DISPLAY_ON_OFF | 0x0
	CURSOR_BLINK_ON  = DISPLAY_ON_OFF | 0x1
	CURSOR_BLINK_OFF = DISPLAY_ON_OFF | 0x0

	CURSOR_DISPLAY_SHIFT = 0x10
	CURSOR_SHIFT_RIGHT   = CURSOR_DISPLAY_SHIFT | 0x4
	CURSOR_SHIFT_LEFT    = CURSOR_DISPLAY_SHIFT | 0x0
	DISPLAY_SHIFT_RIGHT  = CURSOR_DISPLAY_SHIFT | 0xC
	DISPLAY_SHIFT_LEFT   = CURSOR_DISPLAY_SHIFT | 0x8

	FUNCTION_MODE    = 0x20
	DATA_LENGTH_8BIT = FUNCTION_MODE | 0x10
	DATA_LENGTH_4BIT = FUNCTION_MODE | 0x2
	TWO_LINE         = FUNCTION_MODE | 0x8
	ONE_LINE         = FUNCTION_MODE | 0x0
	FONT_5X10        = FUNCTION_MODE | 0x4
	FONT_5X8         = FUNCTION_MODE | 0x0

	BUSY      = 0x80
	CGRAM_SET = 0x40
	DDRAM_SET = 0x80
)
